### ISSUE TITLE
GPU implementation

### ISSUE THREAD

**Issue by marlboroman81** [Limeth/ethaddrgen#2]
I'm appreciate your great work! But could you make a GPU-implementation of ethaddrgen ?
How many times could it be faster if implemented? (for example I'm getting ~200k addresses/second on a 2x 8-core Xeon E5-2660 0 @ 2.20GHz)

**Comment by Limeth** [comment]
I have put some effort into a GPU implementation over at https://github.com/Limeth/vulkanscratch half a year ago, but ran across numerous bugs and, due to that, found the development process incredibly annoying. Especially considering I haven't really done any GPU coding before. I am definitely planning to continue the development, possibly within a month.
As far as speed is concerned, I believe a GPU implementation would let you calculate about another 2 characters in the same amount of time.

**Comment by band1k1** [comment]
Sounds great!

**Comment by Limeth** [comment]
First actual results of the GPU implementation: ![teaser](https://streamable.com/s/b5kcv/ykqapj) :tada: There's still a lot of work that needs to be done, but the finishing line is in sight!

**Comment by avik24** [comment]
Good day! 
I have been using ethaddrgen for over a month and would like to chat about it.
could i contact with you somehow?)

**Comment by Limeth** [comment]
@avik24 Sure thing, send me a message via keybase: https://keybase.io/limeth

**Comment by Limeth** [comment]
I don't currently have an estimate on the release date. As for your question; the currently latest version (1.0.7) generates a random private key and derives an address from it. The first release featuring address generation via the GPU will require sequential generation of private keys, as generating random numbers on the GPU is difficult (you either have to use a pseudo-RNG or you have to "feed" the GPU numbers generated on the CPU, which gets very resource-intensive).

**Comment by roi35** [comment]
Hello, any news GPU implements? Very need

**Comment by Limeth** [comment]
See #7
