### ISSUE TITLE
Private key and address does not match

### ISSUE THREAD

**Issue by zzh1996** [Limeth/ethaddrgen#7]
I compiled master branch (commit ec2dd08). When I run the binary, the generated private key and address does not match.
If I checkout v1.0.7 branch and compile, it works well.

**Comment by Limeth** [comment]
I have made some changes to the master branch in an effort to add GPU acceleration, which resulted in numerous attempts of porting the cryptographic libraries used by the algorithm to GPU-native languages (see https://github.com/Limeth/gfxcomptest and https://github.com/Limeth/vulkanscratch). While working on it, someone has completed a GPU-accelerated vanity address generator for ethereum, and because I found the endeavour too tedious, I abandoned the idea of making my own.
As you said, though, the `v1.0.7` branch contains a fully working CPU implementation.

**Comment by ctrlcctrlv** [comment]
@Limeth So let me get this straight - you're just going to leave the master branch broken, as you have no interest in fixing it because someone else did it before you? And not warn anyone who doesn't stumble across this issue? That's your plan? And just let people waste time and GPU cycles before stumbling across it?

Revert master to v1.0.7 or make a clear warning that master should not be compiled. SMH

# :roll_eyes:

**Comment by Limeth** [comment]
You got me, making people waste CPU cycles was my evil plan all along! This was all orchestrated just to lure people into my trap making them lose their precious CPU cycles!

**Comment by roi35** [comment]
Any news GPU implements?

**Comment by Limeth** [comment]
@roi35 I found out a different vanity address generator on GitHub had GPU support, so I stopped working on mine.
